// Generated by ts-to-zod
import { z } from "zod";

export const futuresBookTickerEventSchema = z.object({
    u: z.number(),
    s: z.string(),
    b: z.string(),
    B: z.string(),
    a: z.string(),
    A: z.string()
});

export const futuresBookDepthEventSchema = z.object({
    lastUpdateId: z.number(),
    bids: z.array(z.tuple([z.string(), z.string()])),
    asks: z.array(z.tuple([z.string(), z.string()]))
});

export const futuresAggTradeEventSchema = z.object({
    e: z.literal("aggTrade"),
    E: z.number(),
    s: z.string(),
    a: z.number(),
    p: z.string(),
    q: z.string(),
    f: z.number(),
    l: z.number(),
    T: z.number(),
    m: z.boolean()
});
